spring:
  datasource:
    url: jdbc:mariadb://localhost:3305/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: zerobase

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

