spring:
  datasource:
    url: jdbc:mariadb://localhost:3305/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: zerobase

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ododieod@gmail.com
    password: aizkxxlabnaqzbul
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root: info

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
